import {createDisconnectedSource} from './data-model/adapter.js';
const base=new URL(document.body.dataset.root,location.href);
const moduleKey=document.body.dataset.module;
const app=document.querySelector('#app');
const h=(tag,attrs={},...children)=>{const e=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')e.className=v;else e.setAttribute(k,v);}for(const c of children.flat(Infinity)){if(c===null||c===undefined)continue;e.append(c instanceof Node?c:document.createTextNode(String(c)));}return e;};
const link=(text,path,attrs={})=>h('a',{href:new URL(path,base).href,...attrs},text);
const pill=(text,type='pending')=>h('span',{class:'pill '+type},text);
const card=(title,desc,...body)=>h('section',{class:'card'},h('div',{class:'card-head'},h('div',{},h('h2',{},title),desc?h('p',{class:'muted small'},desc):null)),...body);
const note=(title,text)=>h('div',{class:'notice'},h('strong',{},title),h('p',{class:'small'},text));
const ul=(items)=>h('ul',{class:'bullet-list'},items.map(x=>h('li',{},x)));
const table=(headers,rows)=>h('div',{class:'table-wrap'},h('table',{},h('thead',{},h('tr',{},headers.map(x=>h('th',{scope:'col'},x)))),h('tbody',{},rows)));
const cells=(xs)=>h('tr',{},xs.map(x=>h('td',{},x)));
const getJson=async path=>{const response=await fetch(new URL(path,base));if(!response.ok)throw new Error(`Unable to load ${path}: ${response.status}`);return response.json();};
try {
const [cfg,dict,events]=await Promise.all([getJson('data-model/console.json'),getJson('data-model/dictionary.json'),getJson('data-model/events.json')]);
const current=cfg.modules.find(x=>x.key===moduleKey);if(!current)throw new Error('Unknown workspace module');
const source=createDisconnectedSource();
const data=await source.readModule(moduleKey);
// Operational data is disconnected: no values, incidents or people are generated.
const sidebar=h('aside',{class:'sidebar',id:'navigation'},link(h('span',{class:'brand-mark'},'PP'),'',{class:'brand'}));
sidebar.firstChild.append(h('span',{},h('strong',{},'Paila Studio OS'),h('small',{},'OWNER WORKSPACE')));
const nav=h('nav',{'aria-label':'Workspace'},h('p',{class:'nav-label'},'Manage the studio'));
for(const m of cfg.modules){if(m.key==='reports')nav.append(h('p',{class:'nav-label'},'Review & improve'));if(m.key==='system')nav.append(link([h('span',{class:'nav-dot'}),'Studio Layout'],'studio/',{class:'nav-link'}));nav.append(link([h('span',{class:'nav-dot'}),m.title],m.path,{class:'nav-link'+(m.key===moduleKey?' active':''),...(m.key===moduleKey?{'aria-current':'page'}:{})}));}
sidebar.append(nav,h('div',{class:'sidebar-footer'},h('strong',{},'v'+cfg.version),h('p',{},'Management framework · data not connected')));
const toggle=h('button',{class:'nav-toggle','aria-controls':'navigation','aria-expanded':'false'},'Menu');toggle.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
const topbar=h('header',{class:'topbar'},toggle,h('span',{class:'topbar-context'},'Paila Pilates / ',h('strong',{},current.title)),h('div',{class:'topbar-links'},pill('Data not connected','neutral'),link('Handbook','sop/'),h('a',{href:'https://pailapilates10-cmd.github.io/Paila-Pilates.com/',target:'_blank',rel:'noopener noreferrer'},'Customer Portal')));
const main=h('main',{id:'main'},h('div',{class:'page-head'},h('div',{},h('div',{class:'eyebrow'},'Owner / management console'),h('h1',{},current.title),h('p',{class:'lede'},current.description)),pill('v'+cfg.version,'neutral')));
main.append(note('No authoritative operational data yet','This public workspace contains the management framework and safe definitions. Actual customers, bookings, payments and staff records require an approved private system. Missing data is never shown as zero.'));
const emptyTable=(headers)=>table(headers,[h('tr',{},h('td',{colspan:String(headers.length),class:'empty-cell'},h('strong',{},'Not connected'),h('span',{},'An approved private source is required before records can appear here.'),h('div',{class:'section'},link('Review data-source readiness','system/',{class:'button'}))))]);
const entityLinks=names=>h('div',{class:'module-links'},names.map(n=>link(n,'data-model/?entity='+encodeURIComponent(n))));
const workflow=(key)=>{const steps=cfg.workflows[key];const list=h('div',{class:'stages',role:'tablist','aria-label':'Workflow stages','aria-orientation':'vertical'});const detail=h('div',{class:'stage-detail',role:'tabpanel',id:'stage-panel',tabindex:'0'});const buttons=[];const set=i=>{buttons.forEach((b,j)=>{b.classList.toggle('selected',j===i);b.setAttribute('aria-selected',String(j===i));b.tabIndex=j===i?0:-1;});const [name,why,event]=steps[i];detail.setAttribute('aria-labelledby','stage-'+i);detail.replaceChildren(h('div',{class:'eyebrow'},'Stage '+(i+1)),h('h3',{},name),h('p',{},why),h('div',{class:'event-label'},h('span',{class:'muted small'},'Event contract'),h('div',{class:'code'},event)),pill('Awaiting source'),h('p',{class:'definition-note'},'This is a workflow definition. No customer or operational record is stored, and no transition or notification is executed.'),link('Inspect event definitions','data-model/#events',{class:'small'}));};steps.forEach(([name],i)=>{const b=h('button',{role:'tab',id:'stage-'+i,'aria-controls':'stage-panel'},h('span',{class:'stage-number'},String(i+1).padStart(2,'0')),name);b.addEventListener('click',()=>set(i));b.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?steps.length-1:(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1)+steps.length)%steps.length;set(j);buttons[j].focus();}});buttons.push(b);list.append(b);});set(0);return h('div',{class:'workflow'},list,detail);};
const sourceList=(subset=cfg.sources)=>h('ul',{class:'list'},subset.map(s=>h('li',{},h('div',{class:'list-title'},h('strong',{},s.name),pill(s.status,s.status.includes('available')?'':'neutral')),h('p',{class:'small muted'},s.need))));
if(moduleKey==='today'){
 const metrics=h('div',{class:'grid four'},['Sessions today','Customer attendance','Net payments','Open operational issues'].map(label=>h('section',{class:'card'},h('div',{class:'metric-label'},label),h('div',{class:'metric-state'},'Awaiting source'),h('div',{class:'metric-note'},'No verified value or refresh time'))));main.append(metrics);
 const attention=h('ul',{class:'list'},[
 ['Connect approved sources','Bookings, attendance, CRM and payments are not connected. Business exceptions cannot yet be assessed.','system/'],
 ['Approve operating definitions','Capacity, cancellation, membership, consent and review policies still require authoritative decisions.','sop/register.html'],
 ['Assign review ownership','Daily close, weekly review and monthly decisions need accountable owners before operational use.','reports/']
 ].map(([t,d,p])=>h('li',{},link([h('h3',{},t),h('p',{class:'small muted'},d)],p,{class:'row-link'}))));
 main.append(h('div',{class:'grid two section'},card('What needs attention','Integration and approval gaps; these are not reported studio incidents.',attention),card('What happened today','A future event feed will supply verified activity.',h('p',{class:'muted'},'Bookings, visits, payments and changes cannot be assessed until their sources are connected.'),emptyTable(['Time','Event','Source']))));
 main.append(h('div',{class:'grid two section'},card('This week','Review participation, conversion, membership movement and unresolved actions.',h('p',{class:'muted'},'No authoritative weekly comparison yet.'),link('Open weekly report framework','reports/?period=Weekly',{class:'button'})),card('Operational readiness','Readiness is unknown until checks and handovers are recorded.',h('p',{class:'muted'},'Opening, equipment availability, cleaning and staffing cannot be verified from this console.'),h('div',{class:'module-links'},link('Studio operations','operations/'),link('Studio Layout · approved preview','studio/')))));
 main.append(h('div',{class:'section'},card('Data-source readiness','No operational feeds are active.',sourceList(),link('View integration requirements','system/',{class:'button'}))));
}else if(cfg.views[moduleKey]){
 const view=cfg.views[moduleKey];main.append(card('Operating view','No authoritative records or fabricated examples.',emptyTable(view.columns)));
 main.append(h('div',{class:'section'},card(moduleKey==='customers'?'Customer lifecycle':'Operating workflow','Select a stage to see the required facts and event.',workflow(moduleKey))));
 main.append(h('div',{class:'grid two section'},card('Exceptions to watch','Definitions only. These conditions are not being evaluated yet.',ul(view.exceptions)),card('Decisions still required','Policy and authority must come from the approved private source.',ul(view.decisions))));
 main.append(h('div',{class:'section'},card('Supporting data contracts','Entity definitions for future integration.',entityLinks(view.entities))));
 if(moduleKey==='operations')main.append(h('div',{class:'section'},card('Studio Layout','Existing approved 2D/3D spatial preview is preserved.',h('p',{class:'muted'},'Use the layout to orient work by zone. Equipment records, inspections and return-to-service decisions remain separate authoritative records.'),link('Open 2D / 3D Studio Layout','studio/',{class:'button'}))));
}else if(moduleKey==='reports'){
 const periods=Object.keys(cfg.reports),tabs=h('div',{class:'tabs',role:'tablist','aria-label':'Review cadence'}),panel=h('section',{role:'tabpanel',id:'report-panel',tabindex:'0'});const bs=[];
 const set=async period=>{await source.readReport(period);bs.forEach(b=>{b.setAttribute('aria-selected',String(b.textContent===period));b.tabIndex=b.textContent===period?0:-1;});panel.setAttribute('aria-labelledby','period-'+period);panel.replaceChildren(card(period+' management review','Definitions are ready for integration. Values, comparisons and refresh times are unavailable.',table(['Review item','Definition / denominator','Authoritative sources','State'],cfg.reports[period].map(r=>cells([r.metric,r.definition,r.sources,pill(r.state,'neutral')])))),h('div',{class:'grid two section'},card('What is changing?','Compare like-for-like periods only after source coverage is verified.',h('p',{class:'muted'},'No verified trend or prior-period comparison yet. An incomplete feed must be flagged rather than interpreted as a fall in activity.')),card('Decisions & follow-through','Future actions link to evidence and a responsible owner.',emptyTable(['Decision','Owner','Due','State']))));};
 periods.forEach((p,i)=>{const b=h('button',{role:'tab',id:'period-'+p,'aria-controls':'report-panel'},p);b.addEventListener('click',()=>set(p));b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const j=(i+(e.key==='ArrowRight'?1:-1)+periods.length)%periods.length;set(periods[j]);bs[j].focus();}});bs.push(b);tabs.append(b);});main.append(tabs,panel);await set(periods.includes(new URLSearchParams(location.search).get('period'))?new URLSearchParams(location.search).get('period'):'Daily');
 main.append(h('div',{class:'section'},card('Reporting rules','All cadences use the same immutable event history.',ul(['Use Asia/Kathmandu for studio reporting boundaries; retain timestamps with an explicit offset.','Deduplicate by event_id and source transaction reference; preserve corrections as new events.','Keep confirmed payments, refunds and recognised revenue distinct; currencies are never silently combined.','Missing coverage, denominator or policy means unavailable, not zero.','Private customer, staff and incident details belong behind role-based access.']))));
}else if(moduleKey==='sops'){
 main.append(h('div',{class:'module-links'},link('Open existing SOP handbook','sop/'),link('Public catalogue','sop/catalog.json')));
 const search=h('input',{type:'search',placeholder:'Search code, title or topic',id:'sop-search'}),filter=h('select',{id:'sop-filter'},['All statuses','Draft','Planned'].map(x=>h('option',{value:x},x))),count=h('span',{class:'small muted','aria-live':'polite'}),body=h('div',{});
 const render=()=>{const q=search.value.toLowerCase();const rows=cfg.sops.filter(x=>(filter.value==='All statuses'||x.status===filter.value)&&[x.code,x.title,x.category,x.reference||''].join(' ').toLowerCase().includes(q));count.textContent=rows.length+' register entries';body.replaceChildren(table(['Code / operating area','Coverage','Status','Owner / approval','Reference'],rows.length?rows.map(s=>cells([[h('span',{class:'code'},s.code),h('div',{},s.title)],s.scope,pill(s.status),[s.owner,h('small',{},'Approval not supplied')],s.href?link(s.reference||'Existing procedure',s.href):h('span',{class:'muted'},'Procedure not yet written')])):[h('tr',{},h('td',{colspan:'5',class:'empty-cell'},'No matching entries'))]));};
 main.append(h('div',{class:'toolbar'},h('label',{for:'sop-search'},'Find procedure',search),h('label',{for:'sop-filter'},'Status',filter),count),card('Master operating register','Four existing procedures plus 26 proposed operating areas. A reference does not mean the procedure fully covers the area.',body));search.addEventListener('input',render);filter.addEventListener('change',render);render();
}else if(moduleKey==='automations'){
 const categories=['All categories','Automatable now','Automatable after data exists','Human review required','Must remain human-controlled'];const select=h('select',{id:'automation-filter'},categories.map(c=>h('option',{value:c},c))),body=h('div',{});const render=()=>body.replaceChildren(table(['Candidate','Category','Trigger / dependency','Review gate','State'],cfg.automations.filter(a=>select.value==='All categories'||a.category===select.value).map(a=>cells([a.name,a.category,[h('span',{class:'code'},a.trigger),h('small',{},a.requires)],a.review,pill(a.status,'neutral')]))));main.append(note('All candidates are inactive','No messages, alerts, payment actions, staffing decisions or safety decisions run from this portal. “Automatable now” describes public contract checks, not an active automation service.'),h('div',{class:'toolbar'},h('label',{for:'automation-filter'},'Category',select)),card('Workflow candidate register','Activate only after authority, complete sources, access controls and review gates are approved.',body));select.addEventListener('change',render);render();
}else if(moduleKey==='system'){
 main.append(h('div',{class:'grid two'},cfg.sources.map(s=>card(s.name,'',h('div',{class:'source-line'},pill(s.status,s.status.includes('available')?'':'neutral')),h('p',{class:'small'},s.need),entityLinks(s.entities)))));
 main.append(h('div',{class:'grid two section'},card('Private integration boundary','Public definitions are ready; private infrastructure is not implemented.',ul(['Approved private datastore and source owners are still required.','Server-side authentication and role-based authorisation must protect every record and endpoint.','Secrets stay on the server; never embed a token in GitHub, a URL or browser storage.','Restrict staff, payment, feedback and incident details by purpose and role.','Apply consent, retention, audit and deletion requirements in the private system.'])),card('Connection acceptance','A connection requires evidence before it may power the owner view.',ul(['Source identity, authority and accountable owner confirmed.','Schema and event IDs validated; duplicates and corrections handled.','Coverage, as-of time, failures and stale data explicitly reported.','Timetable, capacity, pricing and terms sourced from approved records.','An inaccessible or incomplete source renders unavailable, never fabricated values.']))));
 main.append(h('div',{class:'section'},card('Operating-model references','Public evidence informs the framework. Applied patterns below are design inferences, not access to internal manuals.',cfg.benchmarks.map(b=>h('details',{},h('summary',{},b.name+' · '+b.region),h('p',{},b.observed),h('p',{},h('strong',{},'Design inference: '),b.inference),h('p',{},b.coverage+' · checked '+b.checked),h('a',{href:b.url,target:'_blank',rel:'noopener noreferrer'},'Public source'))))));
}else if(moduleKey==='model'){
 const picker=h('select',{id:'entity-select'},dict.entities.map(e=>h('option',{value:e.entity},e.entity))),body=h('div',{});const render=()=>{const entity=dict.entities.find(x=>x.entity===picker.value);body.replaceChildren(card(entity.entity,entity.authority,link('Open JSON schema','data-model/'+entity.schema,{class:'button'}),h('div',{class:'section'},table(['Field','Type','Requirement','Privacy / sensitivity','Authority'],entity.fields.map(f=>cells([h('span',{class:'code'},f.name),f.type,f.requirement,[f.privacy,h('small',{},f.sensitive?'Sensitive reference / field':'Publish only if separately approved')],f.authority]))))));};main.append(note('Definitions are public; records stay private','The dictionary contains 19 entities and field classifications. Required fields belong to the private source contract. Derived fields require validated events and approved definitions; optional facts are omitted when unknown.'),h('div',{class:'toolbar'},h('label',{for:'entity-select'},'Entity',picker),link('Download dictionary','data-model/dictionary.json',{class:'button'})),body);const initial=new URLSearchParams(location.search).get('entity');if(dict.entities.some(e=>e.entity===initial))picker.value=initial;picker.addEventListener('change',()=>{render();const u=new URL(location.href);u.searchParams.set('entity',picker.value);history.replaceState(null,'',u);});render();
 main.append(h('div',{class:'section',id:'events'},card('Event contract','Shared envelope with event-specific required references; no live events are stored here.',h('p',{class:'small muted'},'event_id · event_type · timestamp · location_id · source_system · actor_reference · schema_version · status. Customer, instructor, class, session, booking, membership and other references are required according to the event type. Payment and refund completion additionally require value and currency.'),h('div',{class:'module-links'},link('Event envelope schema','data-model/event.schema.json'),link('Event type registry','data-model/events.json')),h('div',{class:'section'},table(['Event family','Required entity references','Storage'],events.types.map(e=>cells([h('span',{class:'code'},e.type),e.required_references.join(', ')||'Envelope location / actor',e.storage])))))));
}
main.append(h('footer',{class:'footer'},h('span',{},'Paila Studio OS v'+cfg.version+' · framework release'),link('Version / rollback','version.json'),link('Architecture & integration','https://github.com/pailapilates10-cmd/Paila-Pilates-SOP/blob/main/docs/studio-os.md'),h('span',{},'No live operational data · no active automations')));
app.replaceChildren(h('div',{class:'shell'},sidebar,h('div',{class:'workspace'},topbar,main)));
}catch(error){console.error(error);app.replaceChildren(h('main',{id:'main',class:'error'},h('h1',{},'Workspace unavailable'),h('p',{},'The management definitions could not be loaded. No operational data is shown.'),link('Open SOP handbook','sop/',{class:'button'}),link('Open Studio Layout','studio/',{class:'button'}),link('Open public data dictionary','data-model/dictionary.json',{class:'button'})));}
