import {project,cleanState,transitionBooking,report,scenario,stages,ratio,money,classification} from './data-model/prototype-engine.js?v=review-2026-10-03';

export function renderReviewModule(ui) {
 const {moduleKey,main,h,link,pill,card,note,ul,table,cells,seed,research,cfg}=ui;
 const supported=['today','sales','journey','customers','classes','memberships','retention','staff','operations','management','reports','readiness','automations','system'];
 if(!supported.includes(moduleKey))return false;
 const storageKey='paila-fictional-review-2026-10-03';
 let state;try{state=cleanState(seed,JSON.parse(sessionStorage.getItem(storageKey)||'{}'));}catch{state=cleanState(seed);}
 let period='Weekly',stage='All stages',sessionId=seed.sessions[1].id,source='All sources',rhythm='All rhythms',selectedClient=new URLSearchParams(location.search).get('client')||seed.people[0].id;
 let assumptions={fixed:45000,price:11500,variable:15,members:project(seed,state).funnel.active};
 const region=h('div',{id:'review-workspace'}),message=h('p',{class:'small demo-status',role:'status','aria-live':'polite'});
 const save=()=>{state=cleanState(seed,state);try{sessionStorage.setItem(storageKey,JSON.stringify(state));}catch{message.textContent='Browser storage is unavailable. Demo changes last only on this page.';}};
 const button=(label,fn,attrs={})=>{const b=h('button',{type:'button',...attrs},label);b.addEventListener('click',fn);return b;};
 const act=(fn,text)=>{fn();save();render();message.textContent=text||'Fictional demo updated in this browser session only.';};
 const select=(label,values,value,fn)=>{const s=h('select',{'aria-label':label},values.map(v=>h('option',{value:v},v)));s.value=value;s.addEventListener('change',()=>fn(s.value));return h('label',{},label,' ',s);};
 const metric=(label,value,detail)=>h('section',{class:'card prototype-card'},h('div',{class:'metric-label'},label),h('div',{class:'metric-state'},value),h('p',{class:'metric-note'},detail));
 const metrics=rows=>h('div',{class:'grid four section'},rows.map(r=>metric(...r)));
 const list=items=>h('ul',{class:'list'},items.map(x=>h('li',{},x)));
 const empty=text=>h('tr',{},h('td',{colspan:8,class:'empty-cell'},text));
 const clientLink=r=>link(r.name,'journey/?client='+r.id);
 const evidence=key=>{
  const patterns=research.applications.filter(a=>key==='all'||a.feature.toLowerCase().includes(key));
  return card('Research applied to this view','Applied design patterns from the governed feeder; review decisions remain unapproved.',patterns.map(a=>h('details',{},h('summary',{},a.feature),h('p',{},a.decision),h('p',{class:'code'},a.patterns.join(' · ')),h('div',{class:'module-links'},a.sources.map(id=>{const s=research.sources.find(x=>x.id===id);return h('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},id+' · '+s.title);})))),h('p',{class:'definition-note'},research.boundary));
 };
 const actionQueue=p=>table(['Action / evidence','Responsible role','Due / gate','Demo review'],seed.actions.map(a=>cells([[link(a.title,a.route),h('small',{},a.evidence)],a.owner,[a.due,h('small',{},a.gate)],p.state.completed.includes(a.id)?pill('Reviewed in demo','neutral'):button('Mark reviewed (demo)',()=>act(()=>{state.completed.push(a.id);state.log.push(a.id+': Reviewed');}))])));
 const funnel=p=>h('div',{class:'funnel section'},[['Leads',p.funnel.leads,'Recorded enquiries'],['First visits',p.funnel.firstVisits,'Completed visit evidence'],['Second purchases',p.funnel.secondPurchases,'After first visit'],['Active members',p.funnel.active,'Purchase without later exit'],['Exited',p.funnel.exits,'Neutral cancellation evidence']].map(([name,n,d])=>h('div',{class:'card'},h('h3',{},name),h('strong',{class:'metric-state'},n),h('p',{class:'small muted'},d))),h('p',{class:'small muted funnel-note'},'Cumulative fictional cohort through '+seed.asOf+'. Active membership is a current state; exited members are also part of historical conversion. Renewal beyond this snapshot is not assumed.'));
 const clientDetail=(r,p)=>card(r.name+' · '+r.id,'Synthetic service handoff; no contact, health, financial account or private staff detail.',
  pill(r.stage,'prototype'),h('div',{class:'section'},table(['Field','Fictional evidence'],[
   cells(['Goal / preference',r.goal]),cells(['Responsible role',r.owner]),cells(['First / latest completed visit',(r.firstVisit||'Not yet')+' / '+(r.lastVisit||'Not yet')]),cells(['Credits',r.credits+' unused demo credits']),cells(['Next action',r.nextAction]),cells(['Human-review signals',r.reasons.join('; ')||'None under the current demo rules']),cells(['Service boundary','Ask permission and use approved options. No diagnosis or automated persuasion.'])])),h('h3',{class:'section'},'Lifecycle evidence'),table(['Date','Event','Detail'],r.events.map(e=>cells([e.date,e.type,e.reason||e.plan||e.source||(e.first?'Completed first visit':'Completed visit')]))),link('Review retention queue','retention/',{class:'button'}));
 const render=()=>{
  const p=project(seed,state),parts=[];
  const asOf=h('div',{class:'review-meta'},h('span',{},'Fictional snapshot: '+seed.asOf+' · '+seed.asOfTime),pill(state.mode,'neutral'),link('Inspect synthetic source','data-model/review-seed.json'));
  parts.push(asOf);
  if(moduleKey==='today') {
   const capacity=p.sessions.reduce((n,s)=>n+s.availableCapacity,0),occupied=p.sessions.reduce((n,s)=>n+s.occupied,0);
   parts.push(metrics([['Current active members',p.funnel.active,'From fictional purchase and exit events'],['Today’s occupied places',occupied+' / '+capacity,ratio(occupied,capacity)+' of available capacity; held place excluded'],['Human-review signals',p.risks.length,'Explainable participation and friction checks'],['Actions awaiting review',seed.actions.length-state.completed.length,'Marking reviewed acknowledges the demo only']]),h('div',{class:'section'},card('Today’s accountable action queue','Owners, evidence and decision boundaries are visible before an action.',actionQueue(p))),h('div',{class:'grid two section'},card('Today’s sessions','Capacity is a fictional planning assumption, independent of the preserved layout.',table(['Time / session','Places','Readiness'],p.sessions.map(s=>cells([link(s.time+' · '+s.name,'classes/?session='+s.id),s.occupied+' / '+s.availableCapacity,[s.state,h('small',{},s.held?s.held+' place held for inspection':s.waitlisted+' waitlisted')]])))),card('Client journey at a glance','Move to the conversion board to inspect individual handoffs.',ul([p.funnel.leads+' fictional enquiries',p.funnel.firstVisits+' completed first visits',p.funnel.secondPurchases+' second purchases',p.funnel.exits+' cancellation with a neutral reason']),link('Open the working journey board','journey/',{class:'button'}))),h('div',{class:'section'},card('Latest fictional evidence','Business events from the shared seed. Browser demo actions are a separate review log.',table(['Date','Event','Reference'],seed.events.slice(-7).reverse().map(e=>cells([e.date,e.type,e.personId]))))));
  }
  if(['journey','customers','sales'].includes(moduleKey)) {
   parts.push(funnel(p));
   if(moduleKey==='sales') {
    const rows=['Referral','Website','Walk-in','Social'].map(s=>{const rs=p.rows.filter(r=>r.source===s),first=rs.filter(r=>r.firstVisit).length,bought=rs.filter(r=>r.purchases.length).length;return cells([s,rs.length,first,ratio(first,rs.length),bought,ratio(bought,first)]);});
    parts.push(card('Acquisition and conversion by source','Same cumulative cohort. Purchased intro, attended visit and second purchase remain separate concepts.',table(['Source','Leads','Completed first','Lead → first','Second purchase','First → second'],rows)),note('Consultative next step','Use the fictional goal or schedule preference to explain an owner-approved option. This website cannot send an offer, take payment or capture contact details.'));
   }
   const rows=p.rows.filter(r=>(stage==='All stages'||r.stage===stage)&&(source==='All sources'||r.source===source));
   const picker=h('select',{'aria-label':'Inspect fictional client'},p.rows.map(r=>h('option',{value:r.id},r.name)));picker.value=selectedClient;picker.addEventListener('change',()=>{selectedClient=picker.value;render();});
   parts.push(h('div',{class:'toolbar'},select('Journey stage',['All stages',...stages],stage,v=>{stage=v;render();}),select('Lead source',['All sources',...new Set(seed.people.map(r=>r.source))],source,v=>{source=v;render();})),card('Conversion and service board','A next action and responsible role for every fictional record.',table(['Client','Stage / evidence','Goal / source','Next action / owner'],rows.length?rows.map(r=>cells([clientLink(r),[pill(r.stage,'prototype'),h('small',{},'First: '+(r.firstVisit||'pending')+' · Second purchase: '+(r.purchases[0]?.date||'pending'))],[r.goal,h('small',{},r.source)],[r.nextAction,h('small',{},r.owner)]])):[empty('No fictional clients match these filters.')])),h('div',{class:'toolbar'},h('label',{},'Inspect client ',picker)),clientDetail(p.rows.find(r=>r.id===selectedClient)||p.rows[0],p),h('div',{class:'section'},evidence('customer')));
  }
  if(moduleKey==='classes') {
   sessionId=new URLSearchParams(location.search).get('session')&&p.sessions.some(x=>x.id===new URLSearchParams(location.search).get('session'))&&!region.childNodes.length?new URLSearchParams(location.search).get('session'):sessionId;
   const buttons=p.sessions.map(s=>button(s.time+' · '+s.name,()=>{sessionId=s.id;render();},{'aria-pressed':String(s.id===sessionId),class:s.id===sessionId?'selected':''}));
   const s=p.sessions.find(x=>x.id===sessionId),staff=seed.staff.find(t=>t.id===s.staffId);
   const change=(b,status)=>{const r=transitionBooking(seed,state,b.id,status);if(r.ok)state=r.state;save();render();message.textContent=r.message;};
   parts.push(h('div',{class:'tabs','aria-label':'Choose a session'},buttons),metrics([['Fictional capacity',s.capacity,'Not an approved layout or class limit'],['Available after holds',s.availableCapacity,s.held+' held place; only authorised inspection can release'],['Occupied / spaces',s.occupied+' / '+s.spaces,'Booked, checked-in and attended count as occupied'],['Waitlist',s.waitlisted,'Promotion requires an available place']]),card(s.time+' · '+s.name+' · '+s.state,staff.name+' · '+staff.readiness,table(['Client','Booking state','Demo actions'],s.bookings.map(b=>{const r=p.rows.find(r=>r.id===b.personId);let controls=[];
    if(s.state!=='Completed'&&b.status==='Booked')controls=[button('Check in',()=>change(b,'Checked in')),button('Mark no-show',()=>change(b,'No-show')),button('Cancel demo booking',()=>change(b,'Cancelled'))];
    if(b.status==='Waitlisted')controls=[button('Promote if space',()=>change(b,'Booked'),{disabled:s.spaces?null:'disabled'})];
    return cells([clientLink(r),pill(b.status,'neutral'),h('div',{class:'module-links'},controls.length?controls:h('span',{class:'small muted'},s.state==='Completed'?'Completed evidence is read-only':'No further demo transition'))]);}))),note('Attendance and safety boundary','Check-in records arrival only. It does not create a completed visit or deduct credits. Fictional no-show/cancellation does not levy fees. Maintenance holds remain in place; there is no equipment release control.'),h('div',{class:'section'},evidence('capacity')));
  }
  if(moduleKey==='memberships') {
   parts.push(card('Membership and entitlement review','Amounts and credit balances are fictional examples, not an approved Paila offer.',table(['Client','State / option','Remaining credits','Exception / next review'],p.rows.filter(r=>r.purchases.length||r.introCredits).map(r=>cells([clientLink(r),[r.active?'Active demo membership':r.cancellation?'Exited':'Intro only',h('small',{},r.purchases.length?'DEMO-8':'DEMO-INTRO')],r.credits,r.freeze?'Freeze requested; terms not approved':r.cancellation?r.cancellation.reason:r.reasons.join('; ')||'Review next visit'])))),h('div',{class:'grid three section'},seed.plans.map(x=>card(x.name,'FICTIONAL / PROTOTYPE / NOT APPROVED',h('strong',{class:'metric-state'},money(x.price)),h('p',{},x.credits+' fictional visits'),pill('Terms await owner approval','prototype')))),h('div',{class:'section'},card('Respectful freeze and offboarding','A request is evidence, not a policy decision.',ul(['Record a neutral schedule or service reason, without health or personal narratives.','Ask the owner to approve freeze, downgrade, expiry and refund terms before offering them.','Keep the member’s choice and permission visible; no automatic retention message or charge.']),link('Review cancellation and retention evidence','retention/',{class:'button'}))));
  }
  if(moduleKey==='retention') {
   const input=h('input',{type:'number',min:7,max:45,step:1,value:state.lapseDays,'aria-label':'Fictional lapse window in days'});
   const apply=button('Apply demo window',()=>{const n=Number(input.value);if(!Number.isInteger(n)||n<7||n>45){message.textContent='Use a whole number between 7 and 45 days for this fictional scenario.';return;}act(()=>{state.lapseDays=n;});});
   parts.push(h('div',{class:'toolbar'},h('label',{},'Prototype lapse window (days) ',input),apply),note('Explainable signals, human review','The adjustable window is a fictional scenario setting, not an approved policy or churn prediction. Unused credits and booking friction are separate service signals; changing the window does not suppress them.'),card('Participation and service recovery queue','No risk score or automatic outreach. Inspect evidence and context first.',table(['Client','Evidence / reason','Participation','Review action / owner'],p.risks.length?p.risks.map(r=>cells([clientLink(r),r.reasons.join('; '),[r.lastVisit||'No completed visit',h('small',{},r.credits+' unused credits')],[r.nextAction,h('small',{},r.owner)]])):[empty('No fictional records meet the current signal rules.')])),h('div',{class:'grid two section'},card('Freeze and cancellation review','Member autonomy and neutral reasons remain visible.',table(['Client','Evidence','Review gate'],p.rows.filter(r=>r.freeze||r.cancellation).map(r=>cells([clientLink(r),r.freeze?'Freeze requested':r.cancellation.reason,'Owner-approved terms and human review required'])))),card('Client experience rhythm','A proposed service checklist, not an approved SOP.',ul(['Before: clear booking step and session expectations.','During: welcome, respect goal/preferences and provide consistent instruction.','After: acknowledge progress and offer a next step with permission.']),link('Open governed SOP register','sop/register.html',{class:'button'}))),h('div',{class:'section'},evidence('retention')));
  }
  if(moduleKey==='staff') {
   parts.push(card('Roles, readiness and coaching','Entirely fictional instructor aliases. A readiness example does not certify an actual instructor.',table(['Instructor / role','Demo evidence','Development action'],seed.staff.map(t=>cells([[t.name,h('small',{},t.role)],t.readiness,t.coaching])))),h('div',{class:'grid two section'},card('Service observation checklist','Proposed coaching evidence; no popularity ranking.',ul(['Clear arrival and first-visit handoff.','Ask about a client’s goal and legitimate preference respectfully.','Consistent explanation and a suitable next step.','Escalate safety concerns to the authorised person.','Review a peer observation and agree a bounded practice action.'])),card('Delegation boundaries','Role design and readiness precede assignment.',ul(['Front desk: booking clarification and service handoff.','Session lead: teaching readiness and participation evidence.','Membership lead: human review of options and retention context.','Owner: approved policies, staffing terms and material changes.']),link('Management review cadence','management/',{class:'button'}))),h('div',{class:'section'},evidence('daily')));
  }
  if(moduleKey==='operations') {
   parts.push(h('div',{class:'toolbar'},select('Daily rhythm',['All rhythms','Opening','Midday','Closing'],rhythm,v=>{rhythm=v;render();}),link('Open preserved Studio Layout','studio/',{class:'button'})),card('Zone readiness and handover','Fictional task states. Zone labels describe service areas and do not alter the approved drawing.',table(['Rhythm / zone','Task','Responsible role','Demo state / action'],seed.checks.filter(c=>rhythm==='All rhythms'||rhythm===c.rhythm).map(c=>cells([[c.rhythm,h('small',{},c.zone)],c.task,c.owner,c.state.startsWith('Blocked')?pill('Inspection gate — held','prototype'):c.state==='Complete'||state.checks.includes(c.id)?pill('Demo complete','neutral'):button('Complete demo check',()=>act(()=>{state.checks.push(c.id);state.log.push(c.id+': Reviewed');}))])))),note('Open hold / handover','DEMO-S02 retains one held place. Owner or authorised inspector must review real equipment condition before any real release; the demo cannot clear this gate.'),h('div',{class:'section'},evidence('daily')));
  }
  if(moduleKey==='reports') {
   const r=report(seed,period);
   parts.push(h('div',{class:'tabs'},['Daily','Weekly','Monthly'].map(v=>button(v==='Monthly'?'Last 30 days':v,()=>{period=v;render();},{'aria-pressed':String(period===v),class:period===v?'selected':''}))),h('p',{class:'small muted'},'Event window: '+r.start+' through '+r.end+'. Lead cohorts use leads acquired in this window and outcomes observed by the snapshot date.'),metrics([['New enquiries',r.leads,'Lead-created events in this window'],['Completed visits',r.visits,r.firstVisits+' of these are completed first visits'],['Second purchases',r.purchases,'Purchase events after completed first visits'],['Recorded cash receipts',money(r.cash),'Fictional purchase amounts; not recognised revenue or profit']]),h('div',{class:'grid two section'},card('Conversion and membership movement','Counts reconcile to the underlying fictional events.',table(['Measure','Result','Denominator / meaning'],[cells(['Lead → completed first visit',r.firstConversion,r.cohortFirst+' / '+r.leads+' leads in this acquisition cohort']),cells(['First visit → second purchase',r.secondConversion,r.cohortSecond+' / '+r.cohortFirst+' attended in that cohort']),cells(['Current active membership',p.funnel.active,'Snapshot state, not period starts']),cells(['Cancellations in window',r.exits,'Cancellation events, with reasons retained']),cells(['Starting-member churn',r.churn,r.startingMembers+' members active immediately before window; only their cancellations count'])])),card('Interpretation before action','Scenario measures are not targets.',ul(['n/a means the denominator is zero; no percentage is invented.','Current active membership is not equal to all-time second purchases.','Cash receipts do not measure earned revenue, deferred credits or accounting profit.','Demo booking/check-in changes do not rewrite completed-visit evidence.']),link('Open assumptions and decision board','management/',{class:'button'}))),h('div',{class:'section'},card('Event ledger behind this window','Fictional evidence lets reviewers inspect and reconcile each measure.',table(['Date','Event','Client reference','Value / evidence'],r.events.length?r.events.map(e=>cells([e.date,e.type,e.personId,e.amount?money(e.amount):e.reason||e.source||(e.first?'First visit completed':e.type==='visit'?'Repeat visit completed':'—')])):[empty('No fictional events in this window.')]))));
  }
  if(moduleKey==='management') {
   const r=report(seed,'Weekly');
   parts.push(card('Current constraint: preferred-time capacity and participation','Proposed review hypothesis; this does not classify Paila into an external revenue stage.',table(['Decision field','Fictional evidence / bounded plan'],[cells(['Evidence','DEMO-S03: eight occupied places and one waitlisted; DEMO-C07: preferred-time friction and a participation gap.']),cells(['Hypothesis','An alternative supported session could reduce booking friction for affected members.']),cells(['Experiment','Review one alternative time before changing the live timetable; verify instructor coverage, approved capacity and cost.']),cells(['Responsible role / review date','Demo Studio Lead · 2026-10-10']),cells(['Measure next','Waitlist cleared, completed participation, coverage cost and neutral service feedback. No numerical success target is approved.']),cells(['Gate','Owner review before any real schedule, price, staffing or communication change.'])])),h('div',{class:'section'},card('Decision and follow-through board','A review acknowledgement never authorises a real action.',actionQueue(p))),h('div',{class:'grid two section'},card('Management rhythm','Select a constraint from evidence before adding work.',ul(['Daily: readiness, attendance exceptions and next client handoffs.','Weekly: conversion, participation gaps and booking friction.','Monthly: acquisition, membership movement, capacity, financial assumptions and staff development.','After an experiment: compare evidence and choose continue, adjust or stop.']),h('p',{class:'small'},'Weekly fictional snapshot: '+r.visits+' completed visits; '+r.exits+' cancellations.')),card('Owner decision register','Values remain proposed and terms await approval.',table(['Decision','Current state'],[cells(['Purpose, promise and brand standards','Owner review required']),cells(['Prices, credits, cancellation and freeze terms','Fictional options; not approved']),cells(['Staffing, capital and delegation limits','Owner decision; no private amounts loaded']),cells(['Production integrations and automation activation','Disconnected; permissions and source authority required'])]))));
   const controls=h('div',{class:'toolbar'}),output=h('div',{});
   const calculate=()=>{try{const s=scenario(assumptions);output.replaceChildren(table(['Scenario result','Fictional value'],[cells(['Contribution per member',money(s.contribution)]),cells(['Break-even active members',s.breakEven]),cells(['Model monthly revenue',money(s.modelRevenue)]),cells(['Model monthly cost',money(s.modelCost)]),cells(['Model surplus / shortfall',money(s.modelSurplus)])]));}catch{output.replaceChildren(h('p',{role:'status'},'Enter valid scenario assumptions. These are fictional, not Paila financial records.'));}};
   for(const [key,label,min,max] of [['fixed','Fixed monthly cost (NPR)',0,10000000],['price','Average monthly price (NPR)',1,1000000],['variable','Variable cost (%)',0,99],['members','Active members',0,10000]]) {
    const input=h('input',{type:'number',min,max,step:1,value:assumptions[key]});input.addEventListener('input',()=>{const value=Number(input.value);assumptions[key]=input.value!==''&&value>=min&&value<=max?value:NaN;calculate();});controls.append(h('label',{},label,' ',input));
   }
   calculate();parts.push(h('div',{class:'section'},card('Fictional break-even scenario','FICTIONAL / PROTOTYPE / NOT APPROVED. Inputs are illustrative assumptions, not targets, private budgets or accounting advice.',controls,output,h('p',{class:'definition-note'},'Contribution = price × (1 − variable cost %). Break-even = ceiling(fixed cost ÷ contribution). Model surplus excludes tax, capital spending, debt, deferred revenue and refunds. Actual cash receipts remain separate in Reports.'))),h('div',{class:'section'},evidence('capacity')));
  }
  if(moduleKey==='readiness') {
   parts.push(h('div',{class:'toolbar'},select('Planning lens',['Operating review','Pre-opening planning'],state.mode,v=>act(()=>{state.mode=v;}))),note('Optional launch mode','This is a planning lens; it does not assert that Paila is pre-opening or identify its maturity stage. Sample statuses are fictional. No lease, financing, hiring or procurement approval is represented.'),card('Launch dependencies and owner gates','Workstreams can be reviewed together without treating a marketing checklist as operational readiness.',table(['Workstream','Prototype state','Dependency / evidence required','Decision owner'],seed.readiness.map(r=>cells([r.workstream,pill(r.state,'prototype'),r.dependency,r.owner])))),h('div',{class:'grid two section'},card('Presale → first visit → sustained participation','Proposed operating connection, without importing vendor conversion targets.',ul(['Approve an offer and source ownership first.','Track an enquiry through a completed first visit, not just a sold introduction.','Review the next suitable option and membership participation.','Keep staff coverage, capacity and service readiness visible.']),link('Open the shared journey','journey/',{class:'button'})),card('30 / 60 / 90 day review plan','Review assumptions against evidence; no forecasts are presented as actuals.',ul(['30 days: acquisition, first-visit handoffs and daily readiness.','60 days: second purchase, participation gaps and coverage.','90 days: capacity, retention, cash versus earned revenue and owner constraints.']),link('Open management assumptions','management/',{class:'button'}))),h('div',{class:'section'},evidence('launch')));
  }
  if(moduleKey==='automations') {
   parts.push(note('Automation assists human review','This review build executes no real automation. Demo action acknowledgements and class transitions affect only this browser’s fictional state.'),card('Candidate and authority register','All production candidates remain inactive.',table(['Candidate','Trigger / intended assistance','Human gate','State'],cfg.automations.map(a=>cells([a.name,[a.trigger,h('small',{},a.requires)],a.review,pill(a.status,'neutral')])))),card('Working demo controls','The narrow functionality currently implemented.',ul(['Filter and inspect fictional customer stages and service handoffs.','Check in, mark a demo no-show, cancel a fictional booking or promote a waitlisted alias when space exists.','Acknowledge a fictional management review and complete unblocked readiness checks.','Adjust a demo lapse window and numeric financial scenario.','No messaging, payment, policy approval, equipment release or private data writes.'])));
  }
  if(moduleKey==='system') {
   parts.push(card('Connection and public-data boundary','Production operational sources remain disconnected.',table(['Layer','State','Authority'],[cells(['Public review seed','Fictional, event-based, available','Prototype only; not production records']),cells(['Browser demo session','Known synthetic IDs and allowlisted statuses only','Local simulation; resettable; no free-text data collection']),cells(['Private CRM, payments, attendance and staff systems','Not connected','Authenticated server-side system and approved source owners required']),cells(['Customer Portal','Separate outward link','Unchanged separate repository']),cells(['Studio Layout and SOP handbook','Preserved existing files','No spatial changes or procedure approval implied'])])),h('div',{class:'module-links section'},link('Synthetic dataset','data-model/review-seed.json'),link('Research application map','data-model/research-model.json'),link('Production dictionary','data-model/'),link('Approved release / review identity','version.json')),h('div',{class:'section'},evidence('all')),h('div',{class:'section'},card('Feeder evidence quality','Read-back research status, not policy approval.',table(['Source','Evidence state','Public source'],research.sources.map(s=>cells([s.id+' · '+s.title,s.evidence,h('a',{href:s.url,target:'_blank',rel:'noopener noreferrer'},'Open source')]))),h('p',{class:'definition-note'},'VID-005 is a summary-only workshop page. No full-workshop transcript claim is made. Numeric vendor benchmarks and USD stage thresholds are not operational Paila targets.'))));
  }
  if(state.log.length)parts.push(h('div',{class:'section'},card('This browser’s fictional review log','Demo actions are separate from the immutable seed event ledger.',list(state.log.slice(-8).reverse()))));
  region.replaceChildren(...parts);
 };
 const reset=button('Reset fictional demo',()=>{state=cleanState(seed);save();render();message.textContent='Fictional demo reset. No private data or real system was changed.';});
 main.append(h('div',{class:'toolbar'},reset,h('span',{class:'small muted'},'Demo changes persist only in this browser tab’s session.')),message,region);
 render();return true;
}
